version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: css-loader
    versions:
    - "> 4.2.0"
    - "< 5"
  - dependency-name: css-loader
    versions:
    - ">= 5.a"
    - "< 6"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 6.a"
    - "< 7"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 7.a"
    - "< 8"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a"
    - "< 9"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a"
    - "< 10"
